version: "3"
services:
  cataloger-api:
    container_name: cataloger-api
    image: filipe/cataloger
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - "mongodb"
    networks:
      - cataloger-network    
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    networks:
      - cataloger-network
networks:
  cataloger-network:
    driver: bridge